package com.xinghe.zhixue.controller;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
import org.springframework.transaction.annotation.Transactional;
@RestController @RequestMapping("/api/auth")
public class AuthController {
 private final JdbcTemplate db; private final Map<String,Long> sessions=new java.util.concurrent.ConcurrentHashMap<>();
 private final StorageMode storage;
 public AuthController(JdbcTemplate db,StorageMode storage){this.db=db;this.storage=storage;}
 @GetMapping("/config") public Map<String,Object> config(){return Map.of("demoMode",storage.isDemo(),"registrationEnabled",true);}
 @GetMapping("/classes") public List<Map<String,Object>> classes(){return db.queryForList("SELECT id,code,name,grade FROM school_class WHERE enabled=1 ORDER BY grade,name");}
 @PostMapping("/login") public Map<String,Object> login(@RequestBody LoginRequest q){List<Map<String,Object>> r=db.queryForList("SELECT id,username,password_hash,role,display_name FROM sys_user WHERE username=? AND enabled=1",q.username());if(r.isEmpty()||!Passwords.matches(q.password(),String.valueOf(r.get(0).get("password_hash"))))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"账号或密码错误");Map<String,Object> u=view(r.get(0));String t=UUID.randomUUID().toString();sessions.put(t,((Number)u.get("id")).longValue());return Map.of("token",t,"user",u);}
 @PostMapping("/register") @Transactional public Map<String,Object> register(@RequestBody RegisterRequest q){if(q==null||q.username()==null||q.username().isBlank()||q.password()==null||q.password().length()<6)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"账号不能为空，密码至少6位");if(storage.isDemo())return Map.of("registered",false,"message","当前未连接数据库，本次注册未保存。请使用 student、teacher 或 admin 登录，密码均为 123456。");if(!db.queryForList("SELECT id FROM sys_user WHERE username=?",q.username()).isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"账号已存在");String role=("teacher".equals(q.role())?"teacher":"student");List<Long> classIds=q.classIds()==null?List.of():q.classIds();if("student".equals(role)&&classIds.size()>1)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"学生只能选择一个班级");if("teacher".equals(role)&&classIds.size()>2)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"教师最多管理两个班级");try{db.update("INSERT INTO sys_user(username,password_hash,role,display_name) VALUES(?,?,?,?)",q.username(),Passwords.encode(q.password()),role,(q.displayName()==null||q.displayName().isBlank()?q.username():q.displayName()));Long id=db.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,q.username());db.update("INSERT INTO "+role+"_profile(user_id) VALUES(?)",id);for(Long classId:classIds) db.update("INSERT INTO user_class(user_id,class_id) SELECT ?,id FROM school_class WHERE id=? AND enabled=1",id,classId);Map<String,Object> u=view(db.queryForMap("SELECT id,username,role,display_name FROM sys_user WHERE id=?",id));String t=UUID.randomUUID().toString();sessions.put(t,id);return Map.of("token",t,"user",u);}catch(Exception e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"注册失败，请检查数据库表结构");}}
 @GetMapping("/me") public Map<String,Object> me(@RequestHeader(value="X-Auth-Token",required=false)String t){return view(requireUser(t));}
 Map<String,Object> requireUser(String token){Long id=token==null?null:sessions.get(token);if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"请重新登录");List<Map<String,Object>> rows=db.queryForList("SELECT id,username,role,display_name FROM sys_user WHERE id=? AND enabled=1",id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"账号已停用");Map<String,Object> u=rows.get(0);u.put("classes",db.queryForList("SELECT c.id,c.code,c.name,c.grade FROM user_class uc JOIN school_class c ON c.id=uc.class_id WHERE uc.user_id=? AND c.enabled=1 ORDER BY c.grade,c.name",id));return u;}
 long requireAdmin(String token){Map<String,Object> user=requireUser(token);if(!"admin".equals(user.get("role")))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"仅管理员可执行此操作");return ((Number)user.get("id")).longValue();}
 void invalidate(long id){sessions.entrySet().removeIf(e->e.getValue()==id);}
 @PostMapping("/logout") public Map<String,String> logout(@RequestHeader(value="X-Auth-Token",required=false)String t){if(t!=null)sessions.remove(t);return Map.of("message","已退出登录");}
 private Map<String,Object> view(Map<String,Object> r){Map<String,Object> out=new HashMap<>(Map.of("id",r.get("id"),"username",r.get("username"),"role",r.get("role"),"displayName",r.get("display_name")));if(r.containsKey("classes"))out.put("classes",r.get("classes"));return out;}
 record LoginRequest(String username,String password){} record RegisterRequest(String username,String password,String role,String displayName,List<Long> classIds){}
}
